from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1199, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        self.menu_5 = QtWidgets.QMenu(self.menu_3)
        self.menu_5.setObjectName("menu_5")
        self.menu_4 = QtWidgets.QMenu(self.menu_2)
        self.menu_4.setObjectName("menu_4")
        self.menu_6 = QtWidgets.QMenu(self.menu_2)
        self.menu_6.setObjectName("menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_16 = QtWidgets.QAction(MainWindow)
        self.action_16.setObjectName("action_16")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_17 = QtWidgets.QAction(MainWindow)
        self.action_17.setObjectName("action_17")
        self.action_18 = QtWidgets.QAction(MainWindow)
        self.action_18.setObjectName("action_18")
        self.action2px = QtWidgets.QAction(MainWindow)
        self.action2px.setObjectName("action2px")
        self.action4px = QtWidgets.QAction(MainWindow)
        self.action4px.setObjectName("action4px")
        self.action7px = QtWidgets.QAction(MainWindow)
        self.action7px.setObjectName("action7px")
        self.action9px = QtWidgets.QAction(MainWindow)
        self.action9px.setObjectName("action9px")
        self.action12px = QtWidgets.QAction(MainWindow)
        self.action12px.setObjectName("action12px")
        self.action15px = QtWidgets.QAction(MainWindow)
        self.action15px.setObjectName("action15px")
        self.action17px = QtWidgets.QAction(MainWindow)
        self.action17px.setObjectName("action17px")
        self.action20px = QtWidgets.QAction(MainWindow)
        self.action20px.setObjectName("action20px")
        self.action25px = QtWidgets.QAction(MainWindow)
        self.action25px.setObjectName("action25px")
        self.action30px = QtWidgets.QAction(MainWindow)
        self.action30px.setObjectName("action30px")
        self.action35px = QtWidgets.QAction(MainWindow)
        self.action35px.setObjectName("action35px")
        self.action40px = QtWidgets.QAction(MainWindow)
        self.action40px.setObjectName("action40px")
        self.action45px = QtWidgets.QAction(MainWindow)
        self.action45px.setObjectName("action45px")
        self.action50px = QtWidgets.QAction(MainWindow)
        self.action50px.setObjectName("action50px")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_9)
        self.menu_5.addAction(self.action_5)
        self.menu_5.addAction(self.action_1)
        self.menu_5.addAction(self.action_8)
        self.menu_5.addAction(self.action_17)
        self.menu_5.addAction(self.action_18)
        self.menu_3.addAction(self.menu_5.menuAction())
        self.menu_4.addAction(self.action_10)
        self.menu_4.addAction(self.action_11)
        self.menu_4.addAction(self.action_12)
        self.menu_4.addAction(self.action_13)
        self.menu_4.addAction(self.action_14)
        self.menu_6.addAction(self.action2px)
        self.menu_6.addAction(self.action4px)
        self.menu_6.addAction(self.action7px)
        self.menu_6.addAction(self.action9px)
        self.menu_6.addAction(self.action12px)
        self.menu_6.addAction(self.action15px)
        self.menu_6.addAction(self.action17px)
        self.menu_6.addAction(self.action20px)
        self.menu_6.addAction(self.action25px)
        self.menu_6.addAction(self.action30px)
        self.menu_6.addAction(self.action35px)
        self.menu_6.addAction(self.action40px)
        self.menu_6.addAction(self.action45px)
        self.menu_6.addAction(self.action50px)
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.menu_4.menuAction())
        self.menu_2.addAction(self.menu_6.menuAction())
        self.menu_2.addAction(self.action_16)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Инструменты"))
        self.menu_3.setTitle(_translate("MainWindow", "Кисть"))
        self.menu_5.setTitle(_translate("MainWindow", "Стиль"))
        self.menu_4.setTitle(_translate("MainWindow", "Фигуры"))
        self.menu_6.setTitle(_translate("MainWindow", "Размер"))
        self.action.setText(_translate("MainWindow", "Главное меню"))
        self.action_2.setText(_translate("MainWindow", "Сохранить"))
        self.action_3.setText(_translate("MainWindow", "Очистить"))
        self.action_4.setText(_translate("MainWindow", "Вставить"))
        self.action_6.setText(_translate("MainWindow", "Заливка"))
        self.action_7.setText(_translate("MainWindow", "Ластик"))
        self.action_10.setText(_translate("MainWindow", "Линия"))
        self.action_11.setText(_translate("MainWindow", "Круг"))
        self.action_12.setText(_translate("MainWindow", "Прямоугольник"))
        self.action_13.setText(_translate("MainWindow", "Закрашенный круг"))
        self.action_14.setText(_translate("MainWindow", "Закрашенный прямоугольник"))
        self.action_16.setText(_translate("MainWindow", "Цвет"))
        self.action_5.setText(_translate("MainWindow", "Обычный стиль"))
        self.action_1.setText(_translate("MainWindow", "Стиль_1"))
        self.action_8.setText(_translate("MainWindow", "Стиль_2"))
        self.action_17.setText(_translate("MainWindow", "Стиль_3"))
        self.action_18.setText(_translate("MainWindow", "Стиль_4"))
        self.action2px.setText(_translate("MainWindow", "2px"))
        self.action4px.setText(_translate("MainWindow", "4px"))
        self.action7px.setText(_translate("MainWindow", "7px"))
        self.action9px.setText(_translate("MainWindow", "9px"))
        self.action12px.setText(_translate("MainWindow", "12px"))
        self.action15px.setText(_translate("MainWindow", "15px"))
        self.action17px.setText(_translate("MainWindow", "17px"))
        self.action20px.setText(_translate("MainWindow", "20px"))
        self.action25px.setText(_translate("MainWindow", "25px"))
        self.action30px.setText(_translate("MainWindow", "30px"))
        self.action35px.setText(_translate("MainWindow", "35px"))
        self.action40px.setText(_translate("MainWindow", "40px"))
        self.action45px.setText(_translate("MainWindow", "45px"))
        self.action50px.setText(_translate("MainWindow", "50px"))
        self.action_9.setText(_translate("MainWindow", "Выход"))
